### PR TITLE
Add sell stop orders

### PR DESCRIPTION
**Pull request by bookmoons**
Adds sell stop orders to the `matchengine` component. Aiming for fulfillment of the stop loss orders issue #1.

I've taken [this description](https://github.com/cemkod/viabtc_exchange_server/issues/1#issuecomment-408636231) as the target and implemented only sell stop. Trying to post a [buy stop order](https://en.wikipedia.org/wiki/Order_(exchange)#Buy%E2%80%93stop_order) returns an error:

>All I want for the bounty is basic stop-loss order which is a market order with a condition attached that says "this order shall only execute when price drops below X". In other words sell at the best market price when price drops below X.

The HTTP API has a new method `order.put_stop_loss`. The [test file gist](https://gist.github.com/bookmoons/afad68ec11d5d3cf16e4301c2e563201) shows the parameters. Opening a stop loss order freezes the amount and begins watching market price. When a trade drops the price strictly below the `trigger` price, the order is closed and market sell order opened.

The logic is like this:
* Triggering order executed completely.
* All triggered stop loss orders located.
* Each stop loss order converted. Each of these actions can trigger further stop orders.

So it's recursion safe. Everything happens atomically at the important points.

Stop loss orders are not visible in an API dump of the order book, which seems to be the normal way.

There's a schema change to add the `trigger` price. So if you go to test it you'll want to start a fresh database.

The commit history is my working sequence. If you prefer clean commits I can organize.

### CODE REVIEW

**Comment by bookmoons** [comment]
The [test file gist](https://gist.github.com/bookmoons/afad68ec11d5d3cf16e4301c2e563201) runs a test sequence that triggers a stop loss order.

Condition:
```
User 1: stop loss < 90 BCH, sell 1 BTC
User 1: ask 80 BCH for 1 BTC
User 2: bid 20 BCH for 1 BTC
```

Behavior:
* 2 sells 80 BCH at market price. This consumes the 1 BTC at 80 BCH.
* That price is below the stop price. Stop loss order becomes market sell of 1 BTC.
* The market sell consumes the 20 BCH bid.
* End result is 2 bought 2 BTC, 1 bought 100 BCH.

Example run:
```
A = Available
F = Frozen
1: Deposit BTC
    1: BTC A 10000 F 0 / BCH A 0 F 0
    2: BTC A 0 F 0 / BCH A 0 F 0
2: Deposit BCH
    1: BTC A 10000 F 0 / BCH A 0 F 0
    2: BTC A 0 F 0 / BCH A 10000 F 0
2: bid 1 BTC at 20 BCH
    1: BTC A 10000 F 0 / BCH A 0 F 0
    2: BTC A 0 F 0 / BCH A 9980 F 20
1: ask 80 BCH for 1 BTC
    1: BTC A 9999 F 1 / BCH A 0 F 0
    2: BTC A 0 F 0 / BCH A 9980 F 20
1: stop loss, price < 90 BCH, sell 1 BTC
    1: BTC A 9998 F 2 / BCH A 0 F 0
    2: BTC A 0 F 0 / BCH A 9980 F 20
2: sell 80 BCH at market price
    1: BTC A 9998 F 0 / BCH A 100 F 0
    2: BTC A 2 F 0 / BCH A 9900 F 0
Deals:
{u'amount': u'1', u'price': u'80', u'type': u'buy', u'id': 1, u'time': 1539880025.807922}
{u'amount': u'1', u'price': u'20', u'type': u'sell', u'id': 2, u'time': 1539880025.808296}
```

**Comment by cemkod** [comment]
We'll test the commit and get back to you. thank you!

**Comment by cemkod** [comment]
Hello again,

Thank you. We have reviewed the code. It looks clean and does what we asked for. If it passes the tests we are preparing, we'll release the bounty. 

We also want to ask for some additional changes. Can you contact me at jimqode@gmail.com address to discuss the additional changes and pricing?

**Comment by bookmoons** [comment]
>We also want to ask for some additional changes. Can you contact me at jimqode@gmail.com address to discuss the additional changes and pricing?

Thanks very much for the request. Will send an email.

**Comment by bookmoons** [comment]
I'm realizing the ordering might be wrong in nested triggering. What happens now is a triggered sell stop triggers new sell stops immediately. So if the first trigger finds eg 3, the items later in the list might not execute until 20 other sell stops have executed.

I'm not sure now what the typical ordering is on markets. Maybe the thing to do is execute the entire list of located sell stops, and only then trigger new ones. Does that seem right? If that's better I can update.

**Comment by bookmoons** [comment]
There's an exploratory branch with the change I mentioned above:
https://github.com/bookmoons/viabtc_exchange_server/tree/bookmoons/sellstop/ordered

It feels better to me. Trigger everything, then if the price has changed trigger again. It also happens to move the recursion into a tail call.

There's a diff of the changes:
https://github.com/bookmoons/viabtc_exchange_server/compare/bookmoons/stoploss...bookmoons:bookmoons/sellstop/ordered

**Pull request merged**
